##数据库配置
spring:
  datasource:
    url: jdbc:mysql://129.204.205.227:3306/book_drifting?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 3308296
    driver-class-name: com.mysql.cj.jdbc.Driver
## jpa配置
#jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
server:
  port: 8181
#  spring:
#    autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
## 配置日志输出
logging:
  level:
    root: warn
    com.test.vue.dao: trace
  pattern:
    console: '%p%m%n'
    ##配置SQL xml文件路径
mybatis-plus:
  mapper-locations: classpath*:com/fm/famliymoney/mapper/* #sql语句xml文件路径配置
#  config-location: classpath:mybatis-config.xml
  type-aliases-package: com/fm/famliymoney/entity #xml扫描包具体路径配置
#  ##逻辑删除 删除为1 不删除为0
#  global-config:
#    db-config:
#      logic-not-delete-value: 0
#      logic-delete-value: 1
#  global-config:主键配置
#    db-config:
#      id-type: auto
